name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - .github/workflows/docs.yml
  pull_request:
     branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack CIS.EDM.CRPT
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/CIS.EDM.CRPT/CIS.EDM.CRPT.csproj -o .

    # Push packages to Nuget
    - name: Push packages
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

